apiVersion: v1
kind: Service
metadata:
  name: transactions-ihm
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 80
  selector:
    app: transactions-ihm
