apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-config-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.transactionsConfigServer.replicaCount }}
  selector:
    matchLabels:
      app: transactions-config-server
  template:
    metadata:
      labels:
        app: transactions-config-server
    spec:
      containers:
        - image: {{ .Values.transactionsConfigServer.imageName }}:{{ .Values.transactionsConfigServer.imageVersion }}
          name: transactions-config-server
          ports:
            - containerPort: {{ .Values.transactionsConfigServer.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
          - name: CONFIG_PASSPHRASE
            valueFrom:
              secretKeyRef:
                name: transactions-config-credentials
                key: passphrase
          - name: CONFIG_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: transactions-config-credentials
                key: privateKey
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: transactions-config-server-config-map