apiVersion: v1
metadata:
  name: transactions-config-server-config-map
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    server:
      port: {{ .Values.transactionsConfigServer.port }}

    spring:
      cloud:
        config:
          server:
            git:
              uri: {{ .Values.transactionsConfigServer.gitRepo }}
              ignore-local-ssh-settings: true
              passphrase: ${CONFIG_PASSPHRASE}
              privateKey: ${CONFIG_PRIVATEKEY}

    logging:
      level:
        root: {{ .Values.global.logLevel }}
kind: ConfigMap
