apiVersion: v1
metadata:
  name: transactions-ihm-config-map
  namespace: {{ .Values.namespace }}
data:
  config.json: |
    {
      "production": true,
      "transactionsUrl": "http://transactions.127-0-0-1.nip.io/transactions",
      "transactionsUrlGet": "http://transactions.127-0-0-1.nip.io/transactions",
      "keyCloakUrl": "http://keycloak.127-0-0-1.nip.io/realms/transactions",
      "discoveryUrl": "http://keycloak.127-0-0-1.nip.io/realms/transactions/.well-known/openid-configuration",
      "categoriesUrl": "assets/categories.json",
      "bankAccountUrl": "assets/bankAccount.json",
      "redirectUri": "http://localhost"
    }
kind: ConfigMap
