# Default values for transactions-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# TODO : Check if it useful or not
# namespace can be defined through command line. Does all sub charts should be installed in same namespaces
namespace: transactions
namespaceOverride: transactions

global:
  storageClass: local-storage
  logLevel: DEBUG
  namespaceOverride: transactions

# Configuration related to Transactions App Back Office
transactionsBackOffice:
  replicaCount: 1

  imageName: "jugirard/transactions-java-server"
  imageVersion: "v1.3.9.1"

  database:
    capacity: 200Mi

  ingress:
    hostname: "transactions.127-0-0-1.nip.io"

  # Configuration for transactions-java-server app
  config:
    server:
      port: 8080

  persistence: "true"

transactionsIhm:
  replicaCount: 1

  imageName: "jugirard/transactions-ihm-angular"
  imageVersion: "0.1.5.6"

  ingress:
    hostname: "transactions-ihm.127-0-0-1.nip.io"

  config:
    production: true
    transactionsUrl: "someURL"

  assets:
    categories:
      - id: "1"
        label: "Maison"
      - id: "2"
        label: "Voiture"
    bankAccount:
      - id: "1"
        label: "CMB"
      - id: "2"
        label: "Boursorama"

transactionsSync:
  replicaCount: 1

  imageName: "jugirard/transactions-sync-process"
  imageVersion: "v0.1.2"

  ingress:
    hostname: "transactions-sync.127-0-0-1.nip.io"

  config: |
    server.port=8080
    # MongoDB properties
    spring.data.mongodb.host={{ .Values.mongodb.service.nameOverride }}
    spring.data.mongodb.port={{ .Values.mongodb.service.ports.mongodb }}
    spring.data.mongodb.database=transactions
    spring.data.mongodb.uri=mongodb://{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/transactions
    # ES properties
    es.index=transactions
    es.hostname=transactions-es-elasticsearch.elasticsearch.svc.cluster.local:9200
    spring.elasticsearch.rest.uris=http://transactions-es-elasticsearch.elasticsearch.svc.cluster.local:9200

# Configuration sor mongodb subchart
mongodb:
  persistence:
    existingClaim: transactions-data-volume

  service:
    nameOverride: transactions-mongo-db

  auth:
    enabled: false
