apiVersion: batch/v1
kind: CronJob
metadata:
  name: transactions-sync
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.transactionsSync.schedule }}"

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: transactions-sync
        spec:
          containers:
            - image: {{ .Values.transactionsSync.imageName }}:{{ .Values.transactionsSync.imageVersion }}
              name: transactions-sync
              ports:
                - containerPort: 8080
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
              env:
              - name: TARGET_ENV
                value: prod
          restartPolicy: Always
          volumes:
          - name: config-volume
            configMap:
              # Provide the name of the ConfigMap containing the files you want
              # to add to the container
              name: transactions-sync-config-map
