apiVersion: v1
data:
  passphrase: {{ .Values.transactionsConfigServer.passphrase | b64enc }}
  privateKey: {{ .Values.transactionsConfigServer.privateKey | b64enc }}
kind: Secret
metadata:
  name: transactions-config-credentials
  namespace: {{ .Values.namespace }}
type: Opaque