apiVersion: v1
metadata:
  name: transactions-sync-config-map
  namespace: {{ .Values.namespace }}
data:
  application.properties: {{ toYaml .Values.transactionsSync.config | indent 2 }}

kind: ConfigMap
