{{- if eq .Values.transactionsBackOffice.persistence }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-database
  labels:
    type: local
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: transactions-data-volume
    namespace: {{ .Values.namespace }}
  capacity:
    storage: {{ .Values.transactionsBackOffice.database.capacity }}
  local:
    path: /mnt/k8s/data/transactions
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - local
{{- end }}