apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transactions-ihm-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.global.certIssuer }}"
    cert-manager.io/common-name: "{{ .Values.transactionsIhm.ingress.hostname }}"
    cert-manager.io/usages: "server auth"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.transactionsIhm.ingress.hostname }}
      secretName: ingress-transactions-ihm-tls
  rules:
    - host: {{ .Values.transactionsIhm.ingress.hostname }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: transactions-ihm
              port:
                number: 4200