apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.transactionsBackOffice.replicaCount }}
  selector:
    matchLabels:
      app: transactions-back-office
  template:
    metadata:
      labels:
        app: transactions-back-office
    spec:
      containers:
        - image: {{ .Values.transactionsBackOffice.imageName }}:{{ .Values.transactionsBackOffice.imageVersion }}
          name: transactions-back-office
          ports:
            - containerPort: 8080
          env:
          - name: TARGET_ENV
            value: prod
          volumeMounts:
            - name: app-configmap
              mountPath: /etc/config
      restartPolicy: Always
      volumes:
        - name: app-configmap
          configMap:
            name: transactions-server-config-map
