apiVersion: v1
kind: Service
metadata:
  name: transactions-config-server-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "port-config-server"
      port: {{ .Values.transactionsConfigServer.port }}
      targetPort: {{ .Values.transactionsConfigServer.port }}
  selector:
    app: transactions-config-server