{{- if eq .Values.transactionsBackOffice.configMap "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: transactions-server-config-map
  namespace: {{ .Values.namespace }}
data:
  application.yaml:
{{ .Values.transactionsBackOffice.config | toYaml | indent 4 }}
{{- end }}