{{- if eq .Values.transactionsBackOffice.persistence "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transactions-data-volume
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: 200Mi
{{- end }}