apiVersion: v1
kind: Service
metadata:
  name: transactions-sync
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: transactions-sync