apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transactions-back-office-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.global.certIssuer }}"
    cert-manager.io/common-name: "{{ .Values.transactionsBackOffice.ingress.hostname }}"
    cert-manager.io/usages: "server auth"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.transactionsBackOffice.ingress.hostname }}
      secretName: ingress-transactions-back-office-tls
  rules:
    - host: {{ .Values.transactionsBackOffice.ingress.hostname }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: transactions-server
              port:
                number: 8080