
name: Publish Helm Chart

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Add dependency chart repos
      run: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        packages_with_index: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"